### ISSUE TITLE
`stats_are_acquired` test is flakey

### ISSUE THREAD

**Issue by paulgb** [drifting-in-space/spawner#134]
E.g. https://github.com/drifting-in-space/spawner/runs/8142561122?check_suite_focus=true

@pretentious7 how frequent are these checks emitted? I thought 30s would be a long enough time to wait but maybe not.

**Comment by pretentious7** [comment]
it should be, they're limited to DEFAULT_DOCKER_THROTTLED_STATS_INTERVAL_SECS (which is 10 seconds)

**Comment by pretentious7** [comment]
I'm going to set up a script that runs our tests in a cgroup with 10% CPU, will be useful to catch weird racy stuff like this.

**Comment by paulgb** [comment]
I was not able to reproduce the issue, but I believe it still exists, so I'll leave this open for a few weeks and see if we encounter it again.

If we do, we should immediately download the action artifacts (test logs) and attach them to this issue, since they will be overwritten if we re-run the test.

**Comment by paulgb** [comment]
Closing because I haven't seen this in a while and the relevant code has shifted enough that it's probably not relevant.
