### ISSUE TITLE
add per core stats to backend stats message

### ISSUE THREAD

**Issue by pretentious7** [drifting-in-space/spawner#164]

**Comment by paulgb** [comment]
What's the use-case for this?

**Comment by pretentious7** [comment]
Helps with metrics and logging, also brings the backendStats messages in line with droneStats.
 
For example, currently backendStats just says 300% cpu use, which doesn't mean anything without knowing how many cpus there are.

similarly, we should add drone_id to droneStats messages

**Comment by pretentious7** [comment]
actually now that I think about it more, I think they should use the same message

**Comment by rolyatmax** [comment]
A few thoughts:
1. I wonder if we need that level granularity for each backend. If what we really care about is getting an average cpu use, then maybe we should tweak our [cpu percentage calculation](https://github.com/drifting-in-space/spawner/blob/main/core/src/messages/agent.rs#L138) and not multiply by the number of cores? (To be honest, I'm not sure I understand why that's the recommended calculation [here](https://docs.docker.com/engine/api/v1.41/#tag/Container/operation/ContainerStats). It seems like the container's total cpu cycles for a period of time divided by the system's total cpu cycles over that same period should give us the percentage we want. Why multiply by the number of cores?)
2. This could lead to really large message sizes when folks are running on 100-core cpus, for example.

**Comment by pretentious7** [comment]
You're quite right. I think the idea is that if you have `num_cpus` AND `cpu_usage: percentage  * num_cpus`,  you're fine, but that seems, on the face of it, quite bizarre? in fact I'm going to change that right now.

Also agree with the large drone comment.
